### ISSUE TITLE
přidat html značku pro verifikaci FB

### ISSUE THREAD

**Issue by Prazsky-Barcamp** [jakubboucek/prazskybarcamp-web#10]
Ahoj, jak budeš dělat další úpravy o Mili,  mužeš prosím vložit značku pro fB k webu (jistě si tut verifikaci dělal)
Zde sice soubor nevložím, ale pošlu ho mailem
PS až to bude

**Comment by jakubboucek** [comment]
Připomínám @Prazsky-Barcamp tento task. Nemám značku, kterou bych tam mohl dát a na validaci https://www.facebook.com/prazskybarcamp/ nemám práva. Prosím tedy o poslání validační značky.

**Comment by Prazsky-Barcamp** [comment]
DNS značka 
Přidejte TXT záznam do své konfigurace DNS:
facebook-domain-verification=csu30lmeeaz3nn3ydnyto7pjafhk6o
Do pole Hostitel přidejte @ (pokud to vaše doména vyžaduje)
 nebo formou HTML souboru  (pošlu mailem)

**Comment by jakubboucek** [comment]
Nastaveno, ověření: https://toolbox.googleapps.com/apps/dig/#TXT/prazskybarcamp.cz
