### ISSUE TITLE
Error pri zmene hesla

### ISSUE THREAD

**Issue by MiladaKarasova** [jakubboucek/prazskybarcamp-web#12]
![screenshot010](https://user-images.githubusercontent.com/45016369/48440769-11817500-e78a-11e8-893f-d18d1b7ed008.png)

**Comment by jakubboucek** [comment]
To je problém, protože systém se pokouší odeslat e-mail přes SMTP bránu. Ale došlo asi ke změně hesla do e-mailu info@prazskybarcamp.cz, takže na tom to padá.

Klasickou funkci `mail()` nechci používat, protože e-mail by měl odcházet z autentifikovaného serveru (aby nebyl označen jako SPAM), což tato funkce negarantuje.

Možnosti jsou:
- dát tam nové heslo od schránky (jako to bylo nyní), ale to není doporučené, protože se heslo pak nesmí měnit a to není vůbec bezpečné,
- zvolit nějakou jinou odchozí bránu ([AWS SES](https://aws.amazon.com/ses/), [MailGun](https://www.mailgun.com/), [SendGrid](https://sendgrid.com/), nebo český [Ecomail](https://www.ecomail.cz/prehled-funkci)).

**Comment by jakubboucek** [comment]
Vyřešeno nasazení AWS (byť možná jen dočasně)
