### ISSUE TITLE
Integrace Mailchimpu

### ISSUE THREAD

**Issue by jakubboucek** [jakubboucek/prazskybarcamp-web#14]
Navazuji na dnešní telefonát. Prosím o podklady, jak chcete napojit MailChimp.

**Comment by Prazsky-Barcamp** [comment]
Ahoj  dodáno do tabulky s úpravami webu.

**Comment by Prazsky-Barcamp** [comment]
Ale ať to netříštím zde jsou data z Mailchimpu


Posláno mailem

**Comment by Prazsky-Barcamp** [comment]
Kdyžtak se ptej

**Comment by jakubboucek** [comment]
Pavle @Prazsky-Barcamp, jseš si jistý, že ty API klíče tady zveřejňovat je dobrý nápad?!!

**Comment by Prazsky-Barcamp** [comment]
není ale lepší verze mě nenapadla

**Comment by jakubboucek** [comment]
Klient se nevyjádřil, na výzvy nereaguje. Protože včera proběhl Pražský barcamp, považuju issue ze bezpředmětné a zavírám.
