### ISSUE TITLE
Upravy na webu

### ISSUE THREAD

**Issue by Prazsky-Barcamp** [jakubboucek/prazskybarcamp-web#15]
Posílam úpravy pro web, mužeš mi k tomu hodit komentář, co bude v pohodě co ne? Ať vím co se bude v případě potřeby platit. Díky 

Zde oscreenované ukoly.
https://docs.google.com/document/d/16WPECv2ebQopGBBdeyc2DyNqcVn_F0_BK9BK12TVvsc/edit

Kde bude potřeba konzultace dej vědět. (odhaduji u Mailchimpu:)

**Comment by jakubboucek** [comment]
Jak jsme na tom tady? Je tu něco k dodělání, nebo v zásadě úkoly na Mili, popř. Mailchimp, která má vlastní task #14? V takovém případě bych to zavřel, nebo bych z toho vyčlenil nehotové úkoly, abysme se v tom trochu vyznali, co je hotovo a co ne.

**Comment by jakubboucek** [comment]
Tento task zavírám. V dokumentu jsou všechny věci vyřízené, nebo „vyhnily“.

Nově připsaný úkol jsem vyčlenil do #27.
