### ISSUE TITLE
nazelen chyby na webu

### ISSUE THREAD

**Issue by Prazsky-Barcamp** [jakubboucek/prazskybarcamp-web#17]
Ahoj zde je soupis nalezených chyb prosím o rychlou upravu (Mili to ještě projede ale tohle jsem našel já. 

[nalezené chyby na webu.docx](https://github.com/jakubboucek/prazskybarcamp-web/files/2821769/nalezene.chyby.na.webu.docx)
![404](https://user-images.githubusercontent.com/44500312/52126199-fa3a8100-262e-11e9-838c-24ce59983f25.JPG)
![3 zalozka kontakty](https://user-images.githubusercontent.com/44500312/52126200-fa3a8100-262e-11e9-9c5b-e587dbbaaeec.JPG)
![6 zaloha web](https://user-images.githubusercontent.com/44500312/52126202-fad31780-262e-11e9-8b70-36db0b629241.JPG)
![1 kategorie prednasek](https://user-images.githubusercontent.com/44500312/52126203-fad31780-262e-11e9-9d50-2435d65ca2c1.JPG)
![1 recnici zalozka prednasky](https://user-images.githubusercontent.com/44500312/52126204-fad31780-262e-11e9-9131-73566ef25016.JPG)
![1 foto v detailu prednasky](https://user-images.githubusercontent.com/44500312/52126205-fad31780-262e-11e9-93d2-a7c17f2c6c22.JPG)
![2 zalozka o akci](https://user-images.githubusercontent.com/44500312/52126206-fb6bae00-262e-11e9-83cb-3fcc396ddcfe.JPG)
![4 email text u formulare](https://user-images.githubusercontent.com/44500312/52126207-fb6bae00-262e-11e9-8c70-ed9a134135fa.JPG)
![1 speakers](https://user-images.githubusercontent.com/44500312/52126208-fb6bae00-262e-11e9-9ea4-4102d57e78a6.JPG)
![9 rok webu 2018](https://user-images.githubusercontent.com/44500312/52126209-fb6bae00-262e-11e9-9d11-d40e501024f4.JPG)
![5 zalozka partneri](https://user-images.githubusercontent.com/44500312/52126210-fc044480-262e-11e9-936a-1541759a036e.JPG)

**Comment by jakubboucek** [comment]
Většinu chyb jsem opravil hned, posílámk jednotlivým bodm posílám vyjádření:
[nalezene.chyby.na.webu.odpoved.docx](https://github.com/jakubboucek/prazskybarcamp-web/files/2822290/nalezene.chyby.na.webu.odpoved.docx)

**Comment by Prazsky-Barcamp** [comment]
Ještě bych rád věděl kam padají statisticka data, a jak jsou řešeny maily učastníků? a ted konečně valim spát:p

**Comment by jakubboucek** [comment]
Jaká statistická data máš prosím na mysli?

Maily účastníků jsou v adminu s sekci Účastníci, kde je možno je stáhnout do Excelu.

**Comment by jakubboucek** [comment]
Jaká statistická data máš na mysli? 

Maily účastníků jsou dostupné v adminu.

Pokud dobře koukám, všehny připomínky zapracovány, zatím tedy chybí už je Mailchimp. Toto zavírám, protože na Mailchimp je #14.

**Comment by Prazsky-Barcamp** [comment]
V tabulce učastníci mam data dobrá pro Mailchimp (žádna data o věku, škole..) prostě otázkach ve formuláři. A o ty nám šlo především proto se dělal ten formulař. PS kam ty data padají? Rád bych si je prošel
