### ISSUE TITLE
Uprava Designu Nového webu

### ISSUE THREAD

**Issue by Prazsky-Barcamp** [jakubboucek/prazskybarcamp-web#20]
Zde po opravě bugů a dořešení dodáme opět dokument s věcmi pro upravu, neměli by tu byt bugy ani jiné věc řešení dříve. Cílem je více ohnout web směrem k mladší cíloví skupině. PS dodám dokument během zítřka

**Comment by Prazsky-Barcamp** [comment]
https://docs.google.com/document/d/1lZuYij9S-7UFTRQaN0nV2ZplkfzXJPlXSVfWVDhdWUM/edit
Přístup pro tene přídán

**Comment by Prazsky-Barcamp** [comment]
dokumenty O AKCI
https://docs.google.com/document/d/1UdFev5h9kiHg7qTkOelCCMloCVYwJ9beVdvpSMj8m6o/edit

**Comment by Prazsky-Barcamp** [comment]
DOKUMENT: kulate stoly 
https://docs.google.com/document/d/1Lc1Ih75-CJp8IbdfzSGjHY6o9kxh60-6R0ft9GLJMFM/edit
DOKUMENT: být profi  bude během týdne. (zatím nezobrazovat)
DOKUMENT: O AKCI dodán víše. 

FOTO KONTAKTY
![michaela kosikova](https://user-images.githubusercontent.com/44500312/52307799-e464ed00-299b-11e9-866e-6326b782dc59.png)
![jakub rreznicek](https://user-images.githubusercontent.com/44500312/52307801-e5961a00-299b-11e9-8331-659900c2dac8.jpg)
![pavel kosik](https://user-images.githubusercontent.com/44500312/52307808-e8910a80-299b-11e9-93b7-67b0de6e26b1.png)

screen těm co nedodaly fotku
![_herman profilovka](https://user-images.githubusercontent.com/44500312/52307881-2aba4c00-299c-11e9-8c0a-165fb98812d1.png)


Pavel Kosík, Marketing & partneři, kosik@prazskybarcamp.cz, 608037407
kosik@prazskybarcamp.cz
https://www.linkedin.com/in/pavel-kos%C3%ADk/

Milada Karasová, řečníci&dobrovolníci karasova@prazskybarcamp.cz
https://www.linkedin.com/in/milada-karasova/
karasova@prazskybarcamp.cz


Michaela Kosíková: Kulaté stoly&školy 
kosikova@prazskybarcamp.cz
https://www.facebook.com/michaela.cvachova

Jakub Řezníček: školy
reznicek@prazskybarcamp.cz
https://www.facebook.com/jakub.reznicek14

(foto nedodáno)
Pao.bianca Sissak: Marketing sociální sítě
https://www.facebook.com/pabisiss

(foto nedodáno)
Katarina Hradská Projekty & fondy hradska@prazskybarcamp.cz
hradska@prazskybarcamp.cz
https://www.facebook.com/hradska.katarina
https://www.linkedin.com/in/katarina-hradska-bbb82a52/

**Comment by jakubboucek** [comment]
Zavírám, protože to vypadá, že je vše hotovo a jediný zbývající úkol je přenesen do #29.
