### ISSUE TITLE
Chyby v mobilní verzi webu

### ISSUE THREAD

**Issue by MiladaKarasova** [jakubboucek/prazskybarcamp-web#21]
Prosím o úpravu webu v mobilní verzi. Z prokliku (1) Blog (2) a MSoft (3) jsou stránky nenalezeny. V záložce o akci se špatně  zobrazují (4, 5) a ještě detal, jestli by se daly zmenšit ikony soc. sítí, aby byly v jednom řádku (6). Díky. 
![1 mobilni zobrazeni web](https://user-images.githubusercontent.com/45016369/52912499-8cd75300-32b2-11e9-891c-bab177fc9ea9.png)
![2 blog](https://user-images.githubusercontent.com/45016369/52912501-92cd3400-32b2-11e9-81b3-97082999909e.png)
![3 msoft](https://user-images.githubusercontent.com/45016369/52912502-93fe6100-32b2-11e9-9f90-f47b7843bd2b.png)
![4 chyby o akci kstoly](https://user-images.githubusercontent.com/45016369/52912504-95c82480-32b2-11e9-8ae4-d550df55cbcd.png)
![5 chyby o akci foto](https://user-images.githubusercontent.com/45016369/52912505-995bab80-32b2-11e9-87d8-7201101cb962.png)
![6 jen detail ikony soc siti](https://user-images.githubusercontent.com/45016369/52912507-9bbe0580-32b2-11e9-9667-46d32c953586.png)

**Comment by jakubboucek** [comment]
> Blog
Opraveno.

> MSoft
Taková stránka na webu neexistuje, kam je potřeba ji buď vytvořit a nebo počkat, až stránku Google vyhodí z indexu.

> V záložce `o akci` se špatně zobrazují obrázky
Opraveno, obrázky jsou responzvní.

> jestli by se daly zmenšit ikony soc. sítí, aby byly v jednom řádku
Zmenšeny mezery mezi obrázky.
