### ISSUE TITLE
grafické úpravy

### ISSUE THREAD

**Issue by MiladaKarasova** [jakubboucek/prazskybarcamp-web#24]
prosím o 3 úpravy:

![screen prednasky](https://user-images.githubusercontent.com/45016369/53368561-6d42c900-3949-11e9-8363-e05d8d13e38d.png)
[screen přednášky.docx](https://github.com/jakubboucek/prazskybarcamp-web/files/2902590/screen.prednasky.docx)

![text blog](https://user-images.githubusercontent.com/45016369/53368565-6fa52300-3949-11e9-9a4d-f8af14f9ceeb.png)
[text blog.docx](https://github.com/jakubboucek/prazskybarcamp-web/files/2902591/text.blog.docx)

![kulate stoly](https://user-images.githubusercontent.com/45016369/53368991-6ff1ee00-394a-11e9-8bbd-12d2bc241441.png)
[text  - link Kulaté stoly.docx](https://github.com/jakubboucek/prazskybarcamp-web/files/2902610/text.-.link.Kulate.stoly.docx)

**Comment by jakubboucek** [comment]
Vše upraveno, zavírám.

PS: Odkaz na Kulaté stoly je připraven v #28 a čeká na opravu toho cílového webu.
