### ISSUE TITLE
Žádost o nacenění

### ISSUE THREAD

**Issue by MiladaKarasova** [jakubboucek/prazskybarcamp-web#26]
Prosíme o nacenění následujících:

dodat INSTAGRAM ,,okna” (modul)
nastavit (automatické propojení) info přímo do mailchimpu
BLOG - jako Zlínský BC - najít VHODNOU šablonu

**Comment by MiladaKarasova** [comment]
Dodané úpravy k záložce kontakty:
https://docs.google.com/document/d/16WPECv2ebQopGBBdeyc2DyNqcVn_F0_BK9BK12TVvsc/edit
(úplně na konci + dotaz na chyby ve stahování CSV)

**Comment by jakubboucek** [comment]
Pro ostatní body:
- **Propojení Mailchimpu** dle domluveného rozsahu 2-3 hodiny.
- **Změna vzhledu blogu** na vzhled příbuzný ostatnímu webu: 1 hodina.
- **Doplnění administrace** o možnost úpravy údajů, které jsou u účastníků, řečníků a přednášek veřejně viditelné: 1,5 hodiny.
- **Doplnění časů do programu**: 0,5 hodiny.

@MiladaKarasova dotaz:

**Co je prosím „Instagram okno“?** Máte nějaký grafický návrh, popis toho, co byste si 
představovali? Stačí třeba i odkaz na web, kde něco takového mají.
Jestli jste to výpis fotek podobně jako je výpis článků z blogu, tak ~1 hodinu odhadem.

**Comment by jakubboucek** [comment]
Do seznamu nacenění jsem přidal nacenění na úpravu administrace, kterou si vyžádala @MiladaKarasova.

**Comment by jakubboucek** [comment]
Klient se nevyjádřil, na výzvy nereaguje. Protože včera proběhl Pražský barcamp, považuju issue ze bezpředmětné a zavírám.
