### ISSUE TITLE
CSV export 

### ISSUE THREAD

**Issue by jakubboucek** [jakubboucek/prazskybarcamp-web#27]
Úkol z [původního dokumentu](https://docs.google.com/document/d/16WPECv2ebQopGBBdeyc2DyNqcVn_F0_BK9BK12TVvsc/edit):

při EXPORTU CSV souboru přihlášených se párkrát stala chyba. ta spočívala v tom, že daný přednášející se přihlásil a vyplnil všechno a zpětně zjistil, že chce něco upravit a požádál nás o to. my jsme požadavek provedli, ale díky tomu se částečně přemazala jejich dat. Šlo by to odstranit?

**Comment by jakubboucek** [comment]
@MiladaKarasova Díval jsem se do přehledu a nenašel jsem tam žádnou anomálii. V [původním dokumentu](https://docs.google.com/document/d/16WPECv2ebQopGBBdeyc2DyNqcVn_F0_BK9BK12TVvsc/edit) jsi přiložila i screenshot, ale ten byl tam malý, že na něm není vidět nic zvláštního.

Popiš mi prosím, jak se má chyba projevovat?

**Comment by jakubboucek** [comment]
Ještě jednou jsem se podíval a myslím, že už vím, co máš na mysli.

Prvních asi 10 záznamů v tabulce jsou přednášející, které jsem na web dával ručně na vaši žádost. A protože tito neprošli registrací, tak u nich nejsou vyplněny podrobné informace, které jsou u ostatních účastníků.

Týká se to jmen:

- Zbyněk Hyrák
- Martin Jiras
- Radim Kracík
- Karol Veleba
- Jan Kalianko
- David Zábrž
- Jakub Jonáš
- Jakub Oubrecht
- Jakub Rychlý

**Comment by MiladaKarasova** [comment]
Dobře. Prvních 10-ti se to netýká, o nich vím. 
Stalo se to u později přihlášených. Přihlásili se a vše vyplnili. Po uložení chtěli (a s odstupem času) nám zaslali požadavek na úpravu/změnu informací v jejich profilu (konkrétně textu přednášky). Jako admini jsme provedli úpravu a pak při exportování dat se to projevilo tak, že u dotyčného se exportovalo pouze jméno/příjmení/mail/čas registrace a poté celý text, který jsme jim tam jako admini dodávali a tento text vymazal ostatní následující záznamy (město, psč, věk atd...)

**Comment by jakubboucek** [comment]
OK, pak jsem závadný zápis nenašel s prosím o informaci, který konkrétní záznam je špatně. Prostě tam nevidím takový záznam.

Vzhledem k tomu, že tato diskuze zde je veřejná, tak mi tuto informaci prosím pošli jiným kanálem a nebo pošli jen číslo řádku v exportované tabulce.
![image](https://user-images.githubusercontent.com/1657322/53814663-50694f80-3f60-11e9-9ed8-d44e7274db76.png)

**Comment by MiladaKarasova** [comment]
Týkalo se to Jakuba Oubrechta a Tomáše Rusňáka )čísla řádků z hlavy nevím.

*Mi.*

**Comment by jakubboucek** [comment]
**Jakub Oubrecht** (řádek 9) je uveden mezi prvními 10, které byli do systému dány ručně a tedy neprošel registrací.

**Tomáš Rusňák** (řádek 187) má v aktuálním CSV exportu všechny data tak jako kdokoliv jiný. 

Promiň, stále netuším, v čem spatřuješ problém. netvrdím, že není, ale vážně se snažím a nic nevidím.

**Comment by MiladaKarasova** [comment]
Pokud jsi teď data exportoval a byla v pořádku (zejména  *Tomáš Rusňák* (řádek
187) ), tak už žádný problém nespatřuju.

**Comment by jakubboucek** [comment]
Výborně, tedy toto zavírám.

**Comment by MiladaKarasova** [comment]
Jj dik
