### ISSUE TITLE
Bug: záložka přednášky

### ISSUE THREAD

**Issue by MiladaKarasova** [jakubboucek/prazskybarcamp-web#30]
Ahoj, objevila se chyba viz png
Můžeš prosím doplnit a mezi hlavičku a patičku vložit text: **Zveřejnění programu**
                                                                                        Výsledky hlasování se dozvíš 26. 3.

![chybi program](https://user-images.githubusercontent.com/45016369/53757596-5c033a80-3ebc-11e9-9dee-2bf19b9a8baf.png)

**Comment by jakubboucek** [comment]
Dovolil jsem si požadovanou textaci změnit, aby byla v harmonii s textací, která se objeví po zveřejnění programu.
![image](https://user-images.githubusercontent.com/1657322/53761212-4c3c2400-3ec5-11e9-9d54-6d04fe3132f6.png)
