### ISSUE TITLE
error 404 nefunkční link

### ISSUE THREAD

**Issue by MiladaKarasova** [jakubboucek/prazskybarcamp-web#35]
nefunkční link vede na 404

![error 404](https://user-images.githubusercontent.com/45016369/53837490-f5048500-3f92-11e9-99cc-4283637fb865.png)

Původně vedl odkaz na EVENTBRIDE, ale nyní není potřebný. Může to vést na hlavní stránku na část, kde máme informace o místě konání?

**Comment by jakubboucek** [comment]
Ten Microsoft by se tam neměl objevovat vůbec, když na webu není.

To, co požaduješ, to nejde úplně udělat (technicky ano, ale objektivně to porušuje pravidla vyvíjení webu). Postaral jsem se o to, aby se na Googlu objevily odkazy na aktuální web, nikoliv na ten původní a aby si Google naindexoval původní web na původní adrese.

**Comment by MiladaKarasova** [comment]
Ok. Dekuju za vyřešení.

Dne st 6. 3. 2019 0:12 uživatel Jakub Bouček <notifications@github.com>
napsal:
